version: '3.8'

services:
  encore-ui:
    build: .
    ports:
      - "${HOST_PORT:-3000}:${PORT:-3000}"
    environment:
      - VITE_ENCORE_API_URL=${VITE_ENCORE_API_URL:-http://localhost:8080}
      - VITE_ENCORE_BEARER_TOKEN=${VITE_ENCORE_BEARER_TOKEN:-}
      - PORT=${PORT:-3000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${PORT:-3000}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s